// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLoYbaufUMzQ7ntvczdqmHRY2Ud1KBXbo',
    appId: '1:541454661814:web:16c7dc22d130715388ce17',
    messagingSenderId: '541454661814',
    projectId: 'geobible',
    authDomain: 'geobible.firebaseapp.com',
    storageBucket: 'geobible.appspot.com',
    measurementId: 'G-D6GS3QEZ81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkZuOCtWlv5YXvFf4UIPSeqf2Rs3TJwaY',
    appId: '1:541454661814:android:5652cfba77e599af88ce17',
    messagingSenderId: '541454661814',
    projectId: 'geobible',
    storageBucket: 'geobible.appspot.com',
  );
}
