// ignore_for_file: constant_identifier_names

class DataBible {
  static const List<Map<String, dynamic>> DATA = [
    {"order": 1, "name": "Gênesis", "abbr": "Gn", "cap": 50},
    {"order": 2, "name": "Êxodo", "abbr": "Êx", "cap": 40},
    {"order": 3, "name": "Levítico", "abbr": "Lv", "cap": 27},
    {"order": 4, "name": "Números", "abbr": "Nm", "cap": 36},
    {"order": 5, "name": "Deuteronômio", "abbr": "Dt", "cap": 34},
    {"order": 6, "name": "Josué", "abbr": "Js", "cap": 24},
    {"order": 7, "name": "Juízes", "abbr": "Jz", "cap": 21},
    {"order": 8, "name": "Rute", "abbr": "Rt", "cap": 4},
    {"order": 9, "name": "1 Samuel", "abbr": "1Sm", "cap": 31},
    {"order": 10, "name": "2 Samuel", "abbr": "2Sm", "cap": 24},
    {"order": 11, "name": "1 Reis", "abbr": "1Rs", "cap": 22},
    {"order": 12, "name": "2 Reis", "abbr": "2Rs", "cap": 25},
    {"order": 13, "name": "1 Crônicas", "abbr": "1Cr", "cap": 29},
    {"order": 14, "name": "2 Crônicas", "abbr": "2Cr", "cap": 36},
    {"order": 15, "name": "Esdras", "abbr": "Ed", "cap": 10},
    {"order": 16, "name": "Neemias", "abbr": "Ne", "cap": 13},
    {"order": 17, "name": "Ester", "abbr": "Et", "cap": 10},
    {"order": 18, "name": "Jó", "abbr": "Jó", "cap": 42},
    {"order": 19, "name": "Salmos", "abbr": "Sl", "cap": 150},
    {"order": 20, "name": "Provérbios", "abbr": "Pv", "cap": 31},
    {"order": 21, "name": "Eclesiastes", "abbr": "Ec", "cap": 12},
    {"order": 22, "name": "Cantares", "abbr": "Ct", "cap": 8},
    {"order": 23, "name": "Isaías", "abbr": "Is", "cap": 66},
    {"order": 24, "name": "Jeremias", "abbr": "Jr", "cap": 52},
    {"order": 25, "name": "Lamentações", "abbr": "Lm", "cap": 5},
    {"order": 26, "name": "Ezequiel", "abbr": "Ez", "cap": 48},
    {"order": 27, "name": "Daniel", "abbr": "Dn", "cap": 12},
    {"order": 28, "name": "Oseias", "abbr": "Os", "cap": 14},
    {"order": 29, "name": "Joel", "abbr": "Jl", "cap": 3},
    {"order": 30, "name": "Amós", "abbr": "Am", "cap": 9},
    {"order": 31, "name": "Obadias", "abbr": "Ob", "cap": 1},
    {"order": 32, "name": "Jonas", "abbr": "Jn", "cap": 4},
    {"order": 33, "name": "Miqueias", "abbr": "Mq", "cap": 7},
    {"order": 34, "name": "Naum", "abbr": "Na", "cap": 3},
    {"order": 35, "name": "Habacuque", "abbr": "Hc", "cap": 3},
    {"order": 36, "name": "Sofonias", "abbr": "Sf", "cap": 3},
    {"order": 37, "name": "Ageu", "abbr": "Ag", "cap": 2},
    {"order": 38, "name": "Zacarias", "abbr": "Zc", "cap": 14},
    {"order": 39, "name": "Malaquias", "abbr": "Ml", "cap": 4},
    {"order": 40, "name": "Mateus", "abbr": "Mt", "cap": 28},
    {"order": 41, "name": "Marcos", "abbr": "Mc", "cap": 16},
    {"order": 42, "name": "Lucas", "abbr": "Lc", "cap": 24},
    {"order": 43, "name": "João", "abbr": "Jo", "cap": 21},
    {"order": 44, "name": "Atos dos Apóstolos", "abbr": "At", "cap": 28},
    {"order": 45, "name": "Romanos", "abbr": "Rm", "cap": 16},
    {"order": 46, "name": "1 Coríntios", "abbr": "1Co", "cap": 16},
    {"order": 47, "name": "2 Coríntios", "abbr": "2Co", "cap": 13},
    {"order": 48, "name": "Gálatas", "abbr": "Gl", "cap": 6},
    {"order": 49, "name": "Efésios", "abbr": "Ef", "cap": 6},
    {"order": 50, "name": "Filipenses", "abbr": "Fp", "cap": 4},
    {"order": 51, "name": "Colossenses", "abbr": "Cl", "cap": 4},
    {"order": 52, "name": "1 Tessalonicenses", "abbr": "1Ts", "cap": 5},
    {"order": 53, "name": "2 Tessalonicenses", "abbr": "2Ts", "cap": 3},
    {"order": 54, "name": "1 Timóteo", "abbr": "1Tm", "cap": 6},
    {"order": 55, "name": "2 Timóteo", "abbr": "2Tm", "cap": 4},
    {"order": 56, "name": "Tito", "abbr": "Tt", "cap": 3},
    {"order": 57, "name": "Filemom", "abbr": "Fm", "cap": 1},
    {"order": 58, "name": "Hebreus", "abbr": "Hb", "cap": 13},
    {"order": 59, "name": "Tiago", "abbr": "Tg", "cap": 5},
    {"order": 60, "name": "1 Pedro", "abbr": "1Pe", "cap": 5},
    {"order": 61, "name": "2 Pedro", "abbr": "2Pe", "cap": 3},
    {"order": 62, "name": "1 João", "abbr": "1Jo", "cap": 5},
    {"order": 63, "name": "2 João", "abbr": "2Jo", "cap": 1},
    {"order": 64, "name": "3 João", "abbr": "3Jo", "cap": 1},
    {"order": 65, "name": "Judas", "abbr": "Jd", "cap": 1},
    {"order": 66, "name": "Apocalipse", "abbr": "Ap", "cap": 22}
  ];
}
